apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: kaldi-build
spec:
  source:
    type: Binary
  strategy:
    type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: 'kaldi-serve:latest'
