apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: neuralparse
  spec:
    replicas: 1
    selector:
      matchLabels:
        io.kompose.service: neuralparse
    template:
      metadata:
        labels:
          io.kompose.service: neuralparse
      spec:
        containers:
        - image: image-registry.apps.2.rahti.csc.fi/kielipankki-services/neuralparse:latest
          name: neuralparse
          # command:
          #   - /app/neuralparse-init
          ports:
          - containerPort: 7689
          resources:
            limits:
              memory: 4000Mi
            requests:
              memory: 2000Mi
        restartPolicy: Always
kind: List
metadata: {}
