apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  labels:
    io.kompose.service: finnish-forced-align
  metadata:
    name: finnish-forced-align
  namespace: kielipankki-services
  spec:
    ports:
    - port: 5003
      protocol: TCP
      targetPort: 5003
    selector:
      io.kompose.service: finnish-forced-align
kind: List
metadata: {}
