apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  labels:
    io.kompose.service: kaldi-serve
  metadata:
    name: kaldi-serve
  namespace: kielipankki-services
  spec:
    ports:
    - port: 5002
      protocol: TCP
      targetPort: 5002
    selector:
      io.kompose.service: kaldi-serve
kind: List
metadata: {}
