apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  labels:
    io.kompose.service: neuralparse
  metadata:
    name: neuralparse
  namespace: kielipankki-services
  spec:
    ports:
    - port: 7689
      protocol: TCP
      targetPort: 7689
    selector:
      io.kompose.service: neuralparse
kind: List
metadata: {}
