apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  labels:
    io.kompose.service: redis
  metadata:
    name: redis
  namespace: kielipankki-services
  spec:
    ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
    selector:
      io.kompose.service: redis
kind: List
metadata: {}
